name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install compile

      - name: Get Maven version
        run: |
          VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ github.workspace }}/nukkit/target/RedisBridge-Nukkit-${{ env.VERSION }}-SNAPSHOT.jar, ${{ github.workspace }}/waterdogpe/target/RedisBridge-WDPE-${{ env.VERSION }}-SNAPSHOT.jar
          draft: false
          name: Release v${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "The artifacts are kept up to date with the master branch"
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true